#dev
services:
  passive_teacher:
    build:
      #context: contextPath
      dockerfile: dev.dockerfile
    container_name: passive_teacher_app
    #command: ["executable", "arg"]
    ports:
      - 8050:8080
    volumes: 
      - ${APP_DIR}:/app/passive_teacher
    #working_dir:
    # command: tail
    #  -f /dev/null 
    command: ["python3", "-m", "controller.main"]
    depends_on:
      - files_container
    networks:
      - passive_teacher_network


  files_container:
    image: alpine:latest
    container_name: files_container
    ports:
      - 8030:80
    volumes:
      - ${FILES_DIR}:/cheatsheets:ro
    command: ["tail", "-f", "/dev/null"]
    networks:
      - passive_teacher_network
    # depends_on:
    #   - nginx_server




  nginx_server:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 8080:80
    volumes:
      - ${FILES_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf 
    command: ["nginx", "-g", "daemon off;"]  #asegura que nginx se inicalice
    networks:
      - passive_teacher_network
    
    depends_on:
      - files_container
      - passive_teacher



networks:
  passive_teacher_network:
    driver: bridge




