#dev
services:
  passive_teacher:
    build:
      #context: contextPath
      dockerfile: passive_teacher_app_dev.dockerfile
    container_name: passive_teacher_app
    #command: ["executable", "arg"]
    ports:
      - 8050:8080
    volumes: 
      - ${APP_MAIN_DIR}:/app/passive_teacher
    #working_dir:
    # command: tail
    #  -f /dev/null 
    command: ["python3", "-m", "controller.main"]
    depends_on:
      - files_container
    networks:
      - passive_teacher_network


  files_container:
    image: nginx:alpine
    container_name: files_container
    ports:
      - 8030:80
    volumes:
      - ${CHEATSHEETS_DIR}:/usr/share/nginx/html:ro
      - ${NGINX_CONFIG_FILES_CONTAINER}:/etc/nginx/conf.d/default.conf:ro 
    networks:
      - passive_teacher_network
    # depends_on:
    #   - nginx_server



  nginx_server:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - 8080:80
    volumes:
      - ${NGINX_CONFIG_REVERSE_PROXY}:/etc/nginx/conf.d/default.conf 
    command: ["nginx", "-g", "daemon off;"]  #asegura que nginx se inicalice
    networks:
      - passive_teacher_network
    
    depends_on:
      - files_container
      - passive_teacher



networks:
  passive_teacher_network:
    driver: bridge




